/* Mejoras acumulativas v1.4: navegación, instrumentos, entregas y portal familiar. */
(function(){
  const levelOptions=(selected='')=>[['NE','Nivel esperado'],['EN','En desarrollo'],['RA','Requiere apoyo']].map(([code,label])=>`<option value="${code}" ${selected===code?'selected':''}>${code} · ${label}</option>`).join('');
  const currentInstrument=()=> (state.instruments||[]).find(item=>String(item.id)===String($('#classInstrument')?.value||''));

  function renderInstrumentOptions(){
    const select=$('#classInstrument');if(!select)return;
    const previous=select.value;
    select.innerHTML='<option value="">Evaluación sencilla (entrega, conducta y participación)</option>'+(state.instruments||[]).map(item=>`<option value="${escapeHtml(item.id)}">${escapeHtml(item.titulo)} · ${item.tipo==='RUBRICA'?'Rúbrica':'Lista de cotejo'}</option>`).join('');
    if([...select.options].some(option=>option.value===previous))select.value=previous;
    const subject=$('#instrumentSubject');if(subject)subject.innerHTML='<option value="">Todos</option>'+state.subjects.map(item=>`<option>${escapeHtml(item.nombre)}</option>`).join('');
  }
  const originalRenderAll=renderAll;
  renderAll=function(){originalRenderAll();renderInstrumentOptions();renderInstruments()};
  const originalRenderClassOptions=renderClassOptions;
  renderClassOptions=function(){originalRenderClassOptions();renderInstrumentOptions()};

  function renderInstruments(){
    const host=$('#instrumentGrid');if(!host)return;
    const query=($('#instrumentSearch')?.value||'').trim().toLowerCase(),type=$('#instrumentTypeFilter')?.value||'';
    const rows=(state.instruments||[]).filter(item=>(!query||[item.titulo,item.descripcion,item.campoFormativo].join(' ').toLowerCase().includes(query))&&(!type||item.tipo===type));
    host.innerHTML=rows.length?rows.map(item=>`<article class="instrument-card"><div class="instrument-card-head"><span class="instrument-kind ${item.tipo==='RUBRICA'?'rubric':'checklist'}">${item.tipo==='RUBRICA'?'Rúbrica':'Lista de cotejo'}</span><span class="badge">v${item.version||1}</span></div><h2>${escapeHtml(item.titulo)}</h2><p>${escapeHtml(item.descripcion||'Sin descripción')}</p><small>${escapeHtml(item.campoFormativo||'Todos los campos')} · ${(item.criterios||[]).length} criterio(s)</small><ul>${(item.criterios||[]).slice(0,4).map(row=>`<li>${escapeHtml(row.texto)}</li>`).join('')}${(item.criterios||[]).length>4?'<li>…</li>':''}</ul><div class="button-row"><button class="btn small" data-action="edit-instrument" data-id="${escapeHtml(item.id)}">Editar</button><button class="btn small" data-action="duplicate-instrument" data-id="${escapeHtml(item.id)}">Duplicar</button><button class="btn danger small" data-action="deactivate-instrument" data-id="${escapeHtml(item.id)}">Desactivar</button></div></article>`).join(''):'<article class="panel"><strong>No hay instrumentos con esos filtros.</strong><p class="muted">Crea una rúbrica o lista de cotejo para reutilizarla en distintas actividades.</p></article>';
  }
  function criterionRow(value='',weight=1,id=''){return `<div class="instrument-criterion"><input type="hidden" data-criterion-id value="${escapeHtml(id)}"><label>Indicador<input data-criterion-text value="${escapeHtml(value)}" placeholder="Ej. La letra es legible" required></label><label>Peso<input data-criterion-weight type="number" min="0.1" step="0.1" value="${Number(weight)||1}" required></label><button type="button" class="icon-button danger-link" data-action="remove-instrument-criterion" aria-label="Eliminar criterio">×</button></div>`}
  function openInstrument(item=null){
    const form=$('#instrumentForm');form.reset();form.elements.id.value=item?.id||'';form.elements.titulo.value=item?.titulo||'';form.elements.tipo.value=item?.tipo||'RUBRICA';form.elements.campoFormativo.value=item?.campoFormativo||'';form.elements.descripcion.value=item?.descripcion||'';$('#instrumentDialogTitle').textContent=item?'Editar instrumento':'Nuevo instrumento';$('#instrumentCriteria').innerHTML=(item?.criterios?.length?item.criterios:[{texto:'',peso:1},{texto:'',peso:1}]).map(row=>criterionRow(row.texto,row.peso,row.id)).join('');$('#instrumentDialog').showModal();
  }
  async function saveInstrument(event){
    event.preventDefault();const form=event.currentTarget,payload=formData(form);payload.criterios=$$('.instrument-criterion',form).map((row,index)=>({id:$('[data-criterion-id]',row).value||`CRI-${index+1}`,texto:$('[data-criterion-text]',row).value,peso:Number($('[data-criterion-weight]',row).value||1)}));
    await runAction(async()=>{const result=await server('saveEvaluationInstrument',payload);state.instruments=result.instruments||[];$('#instrumentDialog').close();renderInstruments();renderInstrumentOptions();toast(result.message)});
  }
  function updateInstrumentChoice(){const item=currentInstrument(),summary=$('#classInstrumentSummary');if(summary)summary.innerHTML=item?`<b>${escapeHtml(item.titulo)}</b> · ${(item.criterios||[]).length} criterios · niveles NE, EN y RA`:'Puedes evaluar únicamente la entrega o seleccionar una rúbrica/lista de cotejo reutilizable.';renderEvaluationList()}

  defaultEvaluation=function(studentId){return {alumnoId:studentId,trabajo:'Completo',conducta:'Adecuada',participacion:'Media',desempeno:'',observacionLibre:'',instrumentResults:{}}};
  renderEvaluationList=function(){
    const instrument=currentInstrument();
    $('#evaluationList').innerHTML=state.classStudents.length?state.classStudents.map((student,index)=>{const row=state.classEvaluations[student.id]||defaultEvaluation(student.id),selections=row.instrumentResults||{};return `<article class="evaluation-row ${instrument?'with-instrument':''}" data-student="${student.id}"><div class="evaluation-student"><span>${index+1}</span><strong>${escapeHtml(fullName(student))}</strong></div><label>Entrega<select data-field="trabajo"><option ${row.trabajo==='Completo'?'selected':''}>Completo</option><option ${row.trabajo==='Incompleto'?'selected':''}>Incompleto</option><option ${row.trabajo==='No trabajó'?'selected':''}>No trabajó</option></select></label><label>Conducta<select data-field="conducta"><option ${row.conducta==='Excelente'?'selected':''}>Excelente</option><option ${row.conducta==='Adecuada'?'selected':''}>Adecuada</option><option ${row.conducta==='Requiere apoyo'?'selected':''}>Requiere apoyo</option></select></label><label>Participación<select data-field="participacion"><option ${row.participacion==='Alta'?'selected':''}>Alta</option><option ${row.participacion==='Media'?'selected':''}>Media</option><option ${row.participacion==='Nula'?'selected':''}>Nula</option></select></label>${instrument?`<div class="instrument-evaluation"><div class="instrument-evaluation-title"><b>${escapeHtml(instrument.titulo)}</b><span class="instrument-grade" data-grade>—</span></div>${(instrument.criterios||[]).map(criterion=>`<label><span>${escapeHtml(criterion.texto)}</span><select data-instrument-criterion="${escapeHtml(criterion.id)}">${levelOptions(selections[criterion.id]||'NE')}</select></label>`).join('')}</div>`:`<label class="rubric-field">Observación predeterminada<select data-field="desempeno">${rubricOptions(row.desempeno)}</select></label>`}<label class="note-field">Observación adicional<input data-field="observacionLibre" value="${escapeHtml(row.observacionLibre||'')}" placeholder="Opcional"></label></article>`}).join(''):'<div class="empty-history"><strong>No hay alumnos disponibles para evaluar</strong><p>Guarda primero la asistencia del día.</p></div>';
    $('#evaluationProgress').textContent=`${state.classStudents.length} alumno(s) presentes preparados`;if(instrument)$$('.evaluation-row').forEach(updateInstrumentPreview);
  };
  function updateInstrumentPreview(row){const selections={},instrument=currentInstrument();$$('[data-instrument-criterion]',row).forEach(select=>selections[select.dataset.instrumentCriterion]=select.value);const values={NE:10,EN:7,RA:5};let points=0,weights=0;(instrument?.criterios||[]).forEach(c=>{const weight=Number(c.peso||1);points+=(values[selections[c.id]||'RA']/10)*weight;weights+=weight});const grade=weights?Math.round(points/weights*100)/10:null;$('[data-grade]',row).textContent=grade==null?'—':grade.toFixed(1)}
  const originalUpdateClassEvaluation=updateClassEvaluation;
  updateClassEvaluation=function(event){const select=event.target.closest('[data-instrument-criterion]');if(select){const row=select.closest('[data-student]'),record=state.classEvaluations[row.dataset.student];record.instrumentResults=record.instrumentResults||{};record.instrumentResults[select.dataset.instrumentCriterion]=select.value;updateInstrumentPreview(row);return}originalUpdateClassEvaluation(event)};

  function deliveryFilterMatch(student,filter,event){if(filter==='PAGADO_NO_ENTREGADO')return event.requiresDelivery&&student.status==='PAGADO'&&student.deliveryStatus!=='ENTREGADO';if(filter==='ENTREGADO')return event.requiresDelivery&&student.status==='PAGADO'&&student.deliveryStatus==='ENTREGADO';return filter==='TODOS'||student.status===filter}
  renderPaymentDetail=function(){
    const detail=state.paymentDetail;if(!detail)return;const event=detail.event,summary=detail.summary;$('#paymentDetailTitle').textContent=event.name;$('#paymentDetailMeta').textContent=[event.description,formatDateShort(event.date),formatTime(event.time),`Cobro ${paymentMoney(event.charge)} por alumno`,event.requiresDelivery?`Producto: ${event.product||'Sin especificar'}`:''].filter(Boolean).join(' · ');$('[data-action="archive-current-payment-event"]').classList.toggle('hidden-control',!event.active);const cards=[['Pagaron',summary.paidCount],['Abonaron',summary.partialCount],['Pendientes',summary.pendingCount]];if(event.requiresDelivery)cards.push(['Pagado / no entregado',summary.paidNotDeliveredCount],['Entregados',summary.deliveredCount]);cards.push(['Efectivo disponible',paymentMoney(summary.cashAvailable)]);$('#paymentDetailStats').innerHTML=cards.map(([label,value])=>`<div class="stat"><b>${escapeHtml(value)}</b><span>${escapeHtml(label)}</span></div>`).join('');const today=todayCancun();$('#paymentCutForm').elements.date.value=today;$('#paymentMovementForm').elements.date.value=today;renderPaymentStudents();renderPaymentLedgers();renderPaymentFinancial();
  };
  renderPaymentStudents=function(){
    const detail=state.paymentDetail;if(!detail)return;const event=detail.event,query=$('#paymentStudentSearch').value.trim().toLowerCase(),filter=$('#paymentStudentFilter').value;const students=detail.students.filter(student=>deliveryFilterMatch(student,filter,event)&&student.name.toLowerCase().includes(query));$('#paymentStudentList').innerHTML=students.length?students.map((student,index)=>{const paid=student.status==='PAGADO',delivered=student.deliveryStatus==='ENTREGADO';return `<article class="payment-student-row ${delivered?'delivered':''}"><span class="payment-student-number">${index+1}</span><div><strong>${escapeHtml(student.name)}</strong><p>Pagado: ${paymentMoney(student.paid)} · Falta: ${paymentMoney(student.remaining)}</p>${event.requiresDelivery&&delivered?`<small>Entregado ${escapeHtml(formatDateShort(student.deliveryDate))}${student.deliveryReceivedBy?' · Recibió '+escapeHtml(student.deliveryReceivedBy):''}</small>`:''}</div><span class="payment-status ${student.status.toLowerCase()}">${student.status==='PAGADO'?'Pagado':student.status==='ABONO'?'Abono':'No pagado'}</span>${event.requiresDelivery?`<span class="delivery-status ${delivered?'yes':'no'}">${delivered?'Entregado':paid?'No entregado':'Entrega bloqueada'}</span>`:''}<div class="payment-row-actions">${student.remaining>0?`<button class="btn small" data-action="payment-abono" data-id="${escapeHtml(student.id)}">Abono</button><button class="btn primary small" data-action="payment-total" data-id="${escapeHtml(student.id)}">Pagar total</button>`:`<span class="paid-check">✓ Liquidado</span>`}${event.requiresDelivery&&paid?delivered?`<button class="btn small" data-action="undo-payment-delivery" data-id="${escapeHtml(student.id)}">Deshacer entrega</button>`:`<button class="btn primary small" data-action="payment-delivery" data-id="${escapeHtml(student.id)}">Marcar entregado</button>`:''}</div></article>`}).join(''):'<div class="empty-history"><strong>Sin resultados</strong><p>Cambia el filtro o la búsqueda.</p></div>';
  };
  function openDelivery(studentId){const student=state.paymentDetail?.students.find(row=>String(row.id)===String(studentId));if(!student)return;const form=$('#deliveryForm');form.reset();form.elements.studentId.value=student.id;form.elements.date.value=todayCancun();$('#deliveryDialogStudent').textContent=`${student.name} · ${state.paymentDetail.event.product||'Producto'}`;$('#deliveryDialog').showModal()}
  async function saveDelivery(event){event.preventDefault();const payload=formData(event.currentTarget);payload.eventId=state.paymentDetail.event.id;payload.delivered=true;await runAction(async()=>{const result=await server('setPaymentDelivery',payload);state.paymentDetail=result.detail;$('#deliveryDialog').close();renderPaymentDetail();toast(result.message)})}

  function conductGauge(summary){const score=Number(summary?.score),safe=Number.isFinite(score)?Math.max(0,Math.min(10,score)):0,rotation=-90+safe*18,label=summary?.label||'Sin datos';return `<div class="conduct-gauge"><div class="conduct-arc"><i style="transform:rotate(${rotation}deg)"></i></div><div><strong>${escapeHtml(label)}</strong><span>${Number.isFinite(score)?score.toFixed(1)+' de 10':'Sin registros'}</span></div><small><b>Malo</b><b>Regular</b><b>Bueno</b><b>Excelente</b></small></div>`}
  function taskStatusClass(value){return value==='Entregó'?'done':value.includes('incompleta')?'partial':'pending'}
  function familyWeekLabel(start,end){const parse=value=>{const parts=String(value||'').split('-').map(Number);return new Date(parts[0],(parts[1]||1)-1,parts[2]||1)},a=parse(start),b=parse(end),same=a.getMonth()===b.getMonth();return same?`Del ${a.getDate()} al ${b.getDate()} de ${b.toLocaleDateString('es-MX',{month:'long'})}`:`Del ${a.toLocaleDateString('es-MX',{day:'numeric',month:'long'})} al ${b.toLocaleDateString('es-MX',{day:'numeric',month:'long'})}`}
  function taskLine(task){return `<article class="family-task-line ${taskStatusClass(task.status)}"><div><span>${escapeHtml(formatDateShort(task.date))} · ${escapeHtml(formatTime(task.start))}–${escapeHtml(formatTime(task.end))}</span><h4>${escapeHtml(task.name)}</h4><p>${escapeHtml(task.source||'')} · ${escapeHtml(task.project||'Sin proyecto')}</p></div><b>${escapeHtml(task.status)}</b>${task.instrumentGrade!=null?`<small>${escapeHtml(task.instrumentLevel||'Instrumento')} · ${Number(task.instrumentGrade).toFixed(1)}</small>`:''}${task.opportunities?`<p class="opportunity"><b>Área de oportunidad:</b> ${escapeHtml(task.opportunities)}</p>`:''}</article>`}
  renderFamilyAcademic=function(){
    const academic=familyPortalData?.academic;if(!academic)return;const fields=academic.fields||[],summary=academic.taskSummary||{},attendance=academic.attendanceSummary||{},conduct=academic.conductSummary||{},periodLabel=academic.periodLabel||('Trimestre '+(academic.trimester||1)),grades=fields.map(f=>f.grade).filter(v=>v!=null),average=grades.length?grades.reduce((a,b)=>a+Number(b),0)/grades.length:null;$('#familyUpdatedAt').textContent='Actualizado: '+new Date(academic.updatedAt).toLocaleString('es-MX',{dateStyle:'medium',timeStyle:'short'});$('#familyOverview').innerHTML=`<p class="family-period-label">${escapeHtml(periodLabel)}</p><div class="family-overview-grid"><article class="family-metric"><span>Tareas realizadas</span><strong>${summary.completed||0} de ${summary.total||0}</strong><div class="family-progress"><i style="width:${Math.min(summary.percentage||0,100)}%"></i></div><small>${summary.pending||0} pendiente(s)</small></article><article class="family-metric"><span>Promedio provisional</span><strong>${familyNumber(average)}</strong><small>Promedio de los 4 campos formativos</small></article><article class="family-metric"><span>Asistencia del periodo</span><strong>${attendance.attended||0}/${attendance.total||0}</strong><small>${attendance.percentage||0}% · ${attendance.late||0} retardo(s)</small></article><article class="family-metric conduct-metric"><span>Conducta</span>${conductGauge(conduct)}</article></div><article class="family-info-note"><b>Información en proceso.</b> Los resultados cambian cuando el maestro agrega tareas, asistencias, participación, conducta o examen.</article><div class="family-field-preview">${fields.map(field=>`<article><span>${familyFieldIcon(field.name)}</span><div><h3>${escapeHtml(field.name)}</h3><p>${field.completed} de ${field.total} tareas · Calificación ${familyNumber(field.grade)}</p>${field.sources?.length>1?`<small>Matemático ${familyNumber(field.sources[0].grade)} · Científico ${familyNumber(field.sources[1].grade)}</small>`:''}</div></article>`).join('')}</div>`;
    const weeks=academic.weeklyTasks||[];$('#familyTasks').innerHTML=`<div class="family-page-title"><div><p class="eyebrow">${escapeHtml(periodLabel)}</p><h2>Tareas por semana</h2></div><strong>${summary.completed||0} de ${summary.total||0}</strong></div>${weeks.length?weeks.map(week=>`<details class="family-week" ${weeks.length===1?'open':''}><summary><div><b>Semana ${week.number}</b><span>${escapeHtml(familyWeekLabel(week.start,week.end))}</span></div><strong>${week.completed} realizadas · ${week.pending} pendientes</strong></summary><div>${week.tasks.map(taskLine).join('')}</div></details>`).join(''):'<article class="family-card"><p class="muted">No hay actividades registradas en este periodo.</p></article>'}`;$('#familyGrades').innerHTML=familyGradesHtml(fields);
  };

  function enhancePasswords(){
    $$('input[type="password"]').forEach(input=>{if(input.parentElement?.classList.contains('password-wrap'))return;const wrap=document.createElement('span');wrap.className='password-wrap';input.parentNode.insertBefore(wrap,input);wrap.appendChild(input);const button=document.createElement('button');button.type='button';button.className='password-eye';button.textContent='Ver';button.addEventListener('click',()=>{const show=input.type==='password';input.type=show?'text':'password';button.textContent=show?'Ocultar':'Ver'});wrap.appendChild(button);if(input.autocomplete==='new-password'||input.name==='password'&&input.closest('#familyOnboardingForm,#familyRegisterForm,#familyGroupRegisterForm,#familyResetForm,#enrollmentCreateAccountForm')){input.pattern='(?=.*[a-záéíóúñ])(?=.*[A-ZÁÉÍÓÚÑ])(?=.*\\d)(?=.*[^A-Za-zÁÉÍÓÚáéíóúÑñ0-9]).{10,}';input.title='Usa 10 caracteres como mínimo, con mayúscula, minúscula, número y símbolo.';const hint=document.createElement('small');hint.className='password-rules';hint.textContent='10 caracteres como mínimo: mayúscula, minúscula, número y símbolo.';wrap.after(hint)}})
  }
  function addSaveOverlay(){if($('#saveProgressOverlay'))return;document.body.insertAdjacentHTML('beforeend','<div id="saveProgressOverlay" class="save-progress-overlay hidden-control"><div><span>Guardando información…</span><b id="saveProgressValue">0%</b><i><em></em></i></div></div>')}
  function showSaveProgress(){addSaveOverlay();const box=$('#saveProgressOverlay'),bar=$('em',box),value=$('#saveProgressValue');box.classList.remove('hidden-control');let progress=12;bar.style.width=progress+'%';value.textContent=progress+'%';const timer=setInterval(()=>{progress=Math.min(92,progress+Math.ceil((94-progress)/4));bar.style.width=progress+'%';value.textContent=progress+'%'},180);return ()=>{clearInterval(timer);bar.style.width='100%';value.textContent='100%';setTimeout(()=>box.classList.add('hidden-control'),300)}}
  const originalSaveEnrollmentDraft=typeof saveEnrollmentDraft==='function'?saveEnrollmentDraft:null;if(originalSaveEnrollmentDraft)saveEnrollmentDraft=async function(silent=false){const done=showSaveProgress();try{return await originalSaveEnrollmentDraft(silent)}finally{done()}};

  document.addEventListener('DOMContentLoaded',()=>{
    Object.assign(actions,{
      'open-instruments':()=>showView('instruments'),'new-instrument':()=>openInstrument(),'edit-instrument':button=>openInstrument((state.instruments||[]).find(item=>String(item.id)===String(button.dataset.id))),
      'duplicate-instrument':async button=>runAction(async()=>{const result=await server('duplicateEvaluationInstrument',button.dataset.id);state.instruments=result.instruments||[];renderInstruments();renderInstrumentOptions();toast(result.message)}),
      'deactivate-instrument':async button=>{if(!confirm('¿Desactivar este instrumento? Las evaluaciones anteriores se conservarán.'))return;await runAction(async()=>{const result=await server('setEvaluationInstrumentActive',button.dataset.id,false);state.instruments=result.instruments||[];renderInstruments();renderInstrumentOptions();toast(result.message)})},
      'add-instrument-criterion':()=>$('#instrumentCriteria').insertAdjacentHTML('beforeend',criterionRow()),'remove-instrument-criterion':button=>button.closest('.instrument-criterion')?.remove(),
      'payment-delivery':button=>openDelivery(button.dataset.id),'undo-payment-delivery':async button=>{if(!confirm('¿Marcar el producto como no entregado?'))return;await runAction(async()=>{const result=await server('setPaymentDelivery',{eventId:state.paymentDetail.event.id,studentId:button.dataset.id,delivered:false});state.paymentDetail=result.detail;renderPaymentDetail();toast(result.message)})},
      'family-change-account':()=>familyLogout(false,'Sesión cerrada. Ya puede entrar otra familia.')
    });
    $('#instrumentForm')?.addEventListener('submit',saveInstrument);$('#instrumentSearch')?.addEventListener('input',renderInstruments);$('#instrumentTypeFilter')?.addEventListener('change',renderInstruments);$('#classInstrument')?.addEventListener('change',updateInstrumentChoice);$('#deliveryForm')?.addEventListener('submit',saveDelivery);$('#paymentRequiresDelivery')?.addEventListener('change',event=>{const field=$('#paymentProductField');field.classList.toggle('hidden-control',!event.target.checked);field.querySelector('input').required=event.target.checked});
    const collapse=$('#sidebarCollapse');collapse?.addEventListener('click',()=>{const collapsed=$('#sidebar').classList.toggle('collapsed');$('.main').classList.toggle('sidebar-collapsed',collapsed);localStorage.setItem('carpeta_sidebar_collapsed',collapsed?'1':'0')});if(localStorage.getItem('carpeta_sidebar_collapsed')==='1'&&innerWidth>900){$('#sidebar').classList.add('collapsed');$('.main').classList.add('sidebar-collapsed')}
    enhancePasswords();renderInstrumentOptions();renderInstruments();addSaveOverlay();
  });
})();
